CREATE TABLE Users (
    id INT IDENTITY(1,1) PRIMARY KEY,
    username NVARCHAR(50) NOT NULL,
    fullname NVARCHAR(100);
    password NVARCHAR(100) NOT NULL,
    email NVARCHAR(100) NOT NULL,
    phone NVARCHAR(15),
    role NVARCHAR(20) NOT NULL
);

CREATE TABLE 